ifeq ($(OD),debug)
	FLAG=-g -fno-inline -DDEBUG -DBOUNDS_CHECK
endif
ifeq ($(OD),dist)
	FLAG=-O3 -g -DDEBUG
endif
ifeq ($(OD),static)
	FLAG=-O3 -g -DDEBUG
endif
ifeq ($(OD),prof)
	FLAG=-g -pg -O
endif
ifeq ($(OD),opt)
	FLAG=-g -O
endif
ifeq ($(OD),opt2)
	FLAG=-g -O2
endif
ifeq ($(OD),opt3)
	FLAG=-g -O3
endif

#WARN = -W -Wimplicit -Wreturn-type -Wunused -Wswitch -Wcomment -Wformat	\
#       -Wchar-subscripts -Wparentheses -Wcast-qual -Wcast-align         \
#       -Woverloaded-virtual
ARCH	= $(shell uname -i)
BOOST   = /nfs_mount/bioinfo/apps-$(ARCH)/boost/1.48.0
B_INC	= -I$(BOOST)/include
B_LIB	= -L$(BOOST)/lib -Wl,-rpath,$(BOOST)/lib

HDF5=/nfs_mount/bioinfo/apps-x86_64/hdf5-dg/BUILD_3_51
HDF5_include=$(HDF5)/include
HDF5_lib=$(HDF5)/lib
HDF5_link = -Wl,-rpath,$(HDF5_lib)

LINKFLAGS =
STATICLINKFLAGS =
#-Wl,-rpath-link,.
INCLUDE = -I. -I/home/stat/include/cppunit -I/home/stat/include -I/home/stat/lib64/R/include -I../../libraries -I$(HDF5_include) $(B_INC) -I../../samtools/samtools-0.1.19

LARGEFILEFLAGS = -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
CPPFLAGS = -DVERSION=\"$(VERSION)\" $(WARN) $(INCLUDE) $(FLAG) $(LARGEFILEFLAGS)

CC = g++ -fno-merge-constants

LIBDIR =  -L../../samtools/samtools-0.1.19 -L/home/stat/lib64 -L/home/stat/lib-3 -L/home/stat/lib	\
-L../../libraries/BioSequenceTools/$(OD) -L../../libraries/Grace/$(OD) -L../../libraries/bazaar/$(OD) -L$(HDF5_lib)
LIB = $(HDF5_link) $(B_LIB) -lboost_program_options -lboost_serialization -lboost_filesystem -lboost_system -lGraceCPP -lbazaar -lgrace_np -llapack -lbst -ldl -lz -lRmath -lR -lmgcv -lhdf5-dg -lbz2h5 -llzoh5 -lxzh5
LIB2 = $(HDF5_link) $(B_LIB) -lboost_program_options -lboost_serialization -lboost_filesystem -lboost_system -lGraceCPP -lbazaar -lgrace_np -llapack -lbst -ldl -lbam -lz -lRmath -lR -lmgcv -lhdf5-dg -lbz2h5 -llzoh5 -lxzh5 
